"""Generate reference results for the 1D layer-LJ distribution closure."""
from __future__ import annotations

import csv
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from theory.normal_lj_chain import critical_stretch
from theory.normal_lj_distribution import (
    closure_density,
    energy_derivative_at_fixed_mean,
    solve_distribution_closure,
)

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "results" / "data"
FIG_DIR = ROOT / "results" / "figures"


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    mean_stretch = 1.0
    energies = np.asarray([2.0e-4, 5.0e-4, 1.0e-3, 2.0e-3, 4.0e-3])
    solutions = [
        solve_distribution_closure(mean_stretch, float(e), quadrature_order=640)
        for e in energies
    ]

    rows = []
    for e, sol in zip(energies, solutions):
        m = sol.moments
        rows.append(
            {
                "mean_stretch": mean_stretch,
                "mean_energy": float(e),
                "alpha": m.alpha,
                "beta": m.beta,
                "variance_stretch": m.variance_stretch,
                "critical_tail_probability": m.critical_tail_probability,
                "d_energy_d_beta_at_fixed_mean": energy_derivative_at_fixed_mean(m),
            }
        )

    with (DATA_DIR / "normal_lj_distribution_sweep.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    convergence = []
    for order in (240, 320, 480, 640, 800):
        sol = solve_distribution_closure(1.0, 1.0e-3, quadrature_order=order)
        convergence.append({
            "quadrature_order": order,
            "alpha": sol.moments.alpha,
            "beta": sol.moments.beta,
            "tail_probability": sol.moments.critical_tail_probability,
            "variance_stretch": sol.moments.variance_stretch,
        })

    summary = {
        "classification": "controlled large-M saddle-point closure",
        "mean_stretch": mean_stretch,
        "critical_stretch": critical_stretch(),
        "energy_sweep": rows,
        "quadrature_convergence_at_energy_1e-3": convergence,
        "tail_monotone_on_sampled_sweep": all(
            b["critical_tail_probability"] > a["critical_tail_probability"]
            for a, b in zip(rows, rows[1:])
        ),
        "important_limitation": (
            "The closure follows from an equiprobable fixed-length/fixed-energy ensemble "
            "plus a large-M saddle-point approximation. It is not yet derived as the exact "
            "nonequilibrium distribution under cyclic loading."
        ),
    }
    (DATA_DIR / "normal_lj_distribution_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    lam = np.linspace(0.72, 1.42, 900)
    plt.figure(figsize=(8, 5))
    for e, sol in zip(energies, solutions):
        density = closure_density(
            lam,
            sol.moments.alpha,
            sol.moments.beta,
            quadrature_order=640,
        )
        plt.plot(lam, density, label=f"E={e:.1e}")
    plt.axvline(critical_stretch(), linestyle="--", label="lambda_c")
    plt.xlabel("Normalized layer spacing lambda=a/a0")
    plt.ylabel("p_lambda(lambda)")
    plt.title("1D layer-LJ saddle-point distributions at fixed mean")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.savefig(FIG_DIR / "normal_lj_distribution_energy_sweep.svg")
    plt.close()

    plt.figure(figsize=(7, 5))
    plt.plot(
        energies,
        [s.moments.critical_tail_probability for s in solutions],
        marker="o",
    )
    plt.xlabel("Mean shifted LJ energy")
    plt.ylabel("Q_c = Prob(lambda >= lambda_c)")
    plt.title("Normal-opening tail generated by the distribution closure")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(FIG_DIR / "normal_lj_distribution_tail_vs_energy.svg")
    plt.close()

    plt.figure(figsize=(7, 5))
    plt.plot(
        energies,
        [s.moments.variance_stretch for s in solutions],
        marker="o",
    )
    plt.xlabel("Mean shifted LJ energy")
    plt.ylabel("Var(lambda)")
    plt.title("Distribution broadening at fixed mean stretch")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig(FIG_DIR / "normal_lj_distribution_variance_vs_energy.svg")
    plt.close()

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
