#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Milestone 10 exact nonlinear transport를 현재 active 설명으로 동기화한다.

- README에 harmonic/Taylor 전역분포 경로가 superseded되었음을 명시한다.
- Milestone 9를 historical/local diagnostic으로 명시한다.
- OPEN_PROBLEMS의 최우선 과제를 exact F1/P2 hierarchy로 덮어쓴다.
- active result generator에서 harmonic/Taylor push-forward diagnostic을 제외한다.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def insert_after(text: str, anchor: str, block: str, unique_marker: str) -> str:
    if unique_marker in text:
        return text
    idx = text.find(anchor)
    if idx < 0:
        raise RuntimeError(f"anchor not found: {anchor!r}")
    end = idx + len(anchor)
    return text[:end] + "\n\n" + block.strip() + text[end:]


def patch_readme() -> None:
    path = ROOT / "README.md"
    text = path.read_text(encoding="utf-8")
    english = """## Active-theory correction — exact nonlinear transport\n\n**CURRENT ACTIVE STATUS:** the harmonic/single-mode and Taylor-expanded push-forward material retained later in this README is historical/local diagnostic work and is **not** the active global form of $P(\\lambda,t)$.\n\nThe current derivation keeps the original nonlinear generalized-LJ force and starts from the exact empirical transport identities\n\n$$\n\\partial_tP+\\partial_\\lambda J=0,\n$$\n\nwith the spacing-velocity phase-space state $F_1(\\lambda,v,t)$ and neighboring-spacing joint state $P_2$ entering the exact hierarchy. See `docs/MILESTONE10_EXACT_DISTRIBUTION_TRANSPORT.md`.\n\n<!-- ACTIVE_TRANSPORT_CORRECTION_EN -->"""
    korean = """## 활성 이론 정정 — 정확한 비선형 transport\n\n**현재 활성 상태:** 이 README 뒤쪽에 남아 있는 harmonic/single-mode 및 Taylor-expanded push-forward 내용은 historical/local diagnostic이며 $P(\\lambda,t)$의 활성 전역 형식으로 사용하지 않는다.\n\n현재 derivation은 원래 nonlinear generalized-LJ force를 그대로 유지하고 exact empirical transport identity\n\n$$\n\\partial_tP+\\partial_\\lambda J=0\n$$\n\n에서 출발한다. 이후 spacing-velocity phase-space state $F_1(\\lambda,v,t)$와 neighboring-spacing joint state $P_2$가 exact hierarchy에 들어간다. `docs/MILESTONE10_EXACT_DISTRIBUTION_TRANSPORT.md`를 현재 기준으로 사용한다.\n\n<!-- ACTIVE_TRANSPORT_CORRECTION_KO -->"""
    text = insert_after(text, "# Al Fatigue Probability Theory", english, "ACTIVE_TRANSPORT_CORRECTION_EN")
    # Korean section heading currently begins with '# 한국어 번역'.
    if "# 한국어 번역" in text:
        text = insert_after(text, "# 한국어 번역", korean, "ACTIVE_TRANSPORT_CORRECTION_KO")
    path.write_text(text, encoding="utf-8")


def patch_milestone9() -> None:
    path = ROOT / "docs" / "MILESTONE9_GOVERNING_EQUATION_PUSHFORWARD.md"
    text = path.read_text(encoding="utf-8")
    english = """> **SUPERSEDED AS ACTIVE GLOBAL-DISTRIBUTION ROUTE:** Sections below that use linear modes, finite harmonics, or a Taylor expansion about $\\lambda=1$ are retained only as historical/local diagnostics. They are not used for the active full-support distribution theory. The current exact nonlinear route is `MILESTONE10_EXACT_DISTRIBUTION_TRANSPORT.md`.\n\n<!-- M9_SUPERSEDED_EN -->"""
    korean = """> **활성 전역분포 경로에서 제외됨:** 아래의 linear mode, finite harmonic, $\\lambda=1$ 주변 Taylor expansion 부분은 historical/local diagnostic으로만 보존한다. 전체 support의 활성 distribution theory에는 사용하지 않는다. 현재 exact nonlinear 경로는 `MILESTONE10_EXACT_DISTRIBUTION_TRANSPORT.md`다.\n\n<!-- M9_SUPERSEDED_KO -->"""
    text = insert_after(text, "# Milestone 9 — Governing-Equation Push-Forward Clue for the 1D Spacing Distribution", english, "M9_SUPERSEDED_EN")
    ko_anchor = "# 한국어 번역 — 1D Spacing Distribution 형식에 대한 지배방정식 Push-Forward 단서"
    if ko_anchor in text:
        text = insert_after(text, ko_anchor, korean, "M9_SUPERSEDED_KO")
    path.write_text(text, encoding="utf-8")


def patch_open_problems() -> None:
    path = ROOT / "docs" / "OPEN_PROBLEMS.md"
    text = path.read_text(encoding="utf-8")
    english = """## Current priority override — exact nonlinear transport hierarchy\n\nThe earlier equal-measure closure and harmonic/Taylor diagnostics remain falsification references, not the active route. The highest-priority problem is now to derive the exact hierarchy generated by the original nonlinear 1D layer-LJ equation:\n\n$$\nP(\\lambda,t)\n\\leftarrow F_1(\\lambda,v,t)\n\\leftarrow \\text{neighboring joint state }P_2\n\\leftarrow \\cdots\n$$\n\nwithout a global Taylor expansion, finite harmonic ansatz, empirical correlation length, or fitted relaxation law. See Milestone 10.\n\n<!-- OPEN_PROBLEMS_TRANSPORT_EN -->"""
    korean = """## 현재 최우선 과제 — 정확한 비선형 transport hierarchy\n\n기존 equal-measure closure와 harmonic/Taylor diagnostic은 반증 기준으로만 남기고 active route로 사용하지 않는다. 현재 최우선 문제는 원래 nonlinear 1D layer-LJ equation이 만드는 exact hierarchy\n\n$$\nP(\\lambda,t)\n\\leftarrow F_1(\\lambda,v,t)\n\\leftarrow \\text{neighboring joint state }P_2\n\\leftarrow \\cdots\n$$\n\n를 global Taylor expansion, finite harmonic ansatz, empirical correlation length, fitted relaxation law 없이 유도하는 것이다. Milestone 10을 기준으로 한다.\n\n<!-- OPEN_PROBLEMS_TRANSPORT_KO -->"""
    text = insert_after(text, "# Open Problems — Active 1D Layer-LJ Mainline", english, "OPEN_PROBLEMS_TRANSPORT_EN")
    ko_anchor = "# 한국어 번역 — 활성 1D Layer-LJ Mainline 미해결 문제"
    if ko_anchor in text:
        text = insert_after(text, ko_anchor, korean, "OPEN_PROBLEMS_TRANSPORT_KO")
    path.write_text(text, encoding="utf-8")


def patch_generator() -> None:
    path = ROOT / "simulations" / "generate_results.py"
    text = path.read_text(encoding="utf-8")
    text = text.replace(
        "from simulations.run_normal_lj_pushforward_clue import main as run_normal_pushforward_clue\n",
        "",
    )
    text = text.replace("    run_normal_pushforward_clue()\n", "")
    path.write_text(text, encoding="utf-8")


def main() -> None:
    patch_readme()
    patch_milestone9()
    patch_open_problems()
    patch_generator()
    print("Exact nonlinear transport supersession synchronized.")


if __name__ == "__main__":
    main()
