"""Structural interface shared by analytic local two-coordinate energies."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

import numpy as np


@runtime_checkable
class LocalEnergySurface(Protocol):
    """Minimum interface required by the N=1 probability/energy diagnostics."""

    p: object
    a0: float

    def energy(self, a: float, s: float) -> float: ...

    def grad(self, a: float, s: float) -> np.ndarray: ...

    def hessian(self, a: float, s: float) -> np.ndarray: ...

    def local_energy(self, a: float, s: float) -> float: ...

    def local_deda(self, a: float, s: float) -> float: ...

    def local_deds(self, a: float, s: float) -> float: ...

    def local_deda_array(self, a, s: float): ...

    def local_energy_gradient_array(self, a, s): ...

    def local_hessian(self, a: float, s: float) -> np.ndarray: ...

    def sigma_over_E_force_scale(self) -> float: ...

    def force_from_sigma_over_E(self, sigma_over_E): ...

    def energy_gradient(self, a: np.ndarray, s: np.ndarray, force: float): ...

    def energy_gradient_batch(self, a: np.ndarray, s: np.ndarray, force: float): ...

    def opening_saddle_batch(self, s: np.ndarray, force: float): ...
