import csv
import hashlib
import json
from pathlib import Path

import numpy as np
import pytest

from .yield_reference_data import PIGATO_DOI, parse_pigato_yield_xml


def table_fixture():
    """Small parser fixture, not an additional experimental source."""
    rows = [('YS(MPa)', '+25', '16.4 ± 1.3', '74.6 ± 3.7', '34.1 ± 1.1'),
            ('−50', '19.0 ± 2.3', '82.9 ± 1.6', '35.5'),
            ('−100', '21.2', '88.5 ± 3.8', '37.0'),
            ('−150', '24.2', '83.1', '58.5')]
    body = ''
    for i, row in enumerate(rows):
        body += '<tr>' + ''.join(('<td rowspan="4">' if i == 0 and j == 0 else '<td>')
                                +cell+'</td>' for j, cell in enumerate(row))+'</tr>'
    return (f'<article><article-id pub-id-type="doi">{PIGATO_DOI}</article-id>'
            '<article-title>parser fixture</article-title><table-wrap><label>Table 2</label>'
            '<table><thead><tr><th></th><th>Temperature (°C)</th><th>6N</th><th>5N5</th><th>5N</th>'
            '</tr></thead><tbody>'+body+'</tbody></table></table-wrap></article>').encode('utf-8')


def test_twelve_source_values_conditions_and_unit_conversion():
    rows = parse_pigato_yield_xml(table_fixture())
    assert len(rows) == 12
    assert [r['reported_tensile_YS_MPa'] for r in rows[:3]] == [16.4, 74.6, 34.1]
    assert rows[0]['temperature_K'] == 298.15
    assert rows[9]['temperature_K'] == pytest.approx(123.15)
    assert rows[5]['reported_uncertainty_MPa'] is None
    assert rows[0]['microstructure'] != rows[1]['microstructure']
    assert len(set(r['id'] for r in rows)) == 12
    for row in rows:
        assert row['plastic_strain_criterion'] is None
        assert row['source_pin_spacing_m'] is None
        assert not row['used_in_fit'] and not row['comparable_to_current_source_model']


@pytest.mark.parametrize('before,after', [('YS(MPa)', 'YS(GPa)'), ('ma19061195', 'wrong'), ('Table 2', 'Table 3')])
def test_wrong_source_or_units_refused(before, after):
    with pytest.raises(ValueError):
        parse_pigato_yield_xml(table_fixture().replace(before.encode(), after.encode()))


def test_saved_actual_study_preserves_unknowns_and_rejects_specimen_yield():
    # Generated by the actual runner; no external download in the test suite.
    root = Path(__file__).resolve().parents[1]/'results/specimen_yield_bridge_v21'
    with (root/'reported_yield_references.csv').open(encoding='utf-8', newline='') as stream:
        rows = list(csv.DictReader(stream))
    assert len(rows) == 12
    for row in rows:
        assert row['plastic_strain_criterion'] == ''
        assert row['source_pin_spacing_m'] == ''
        assert row['used_in_fit'] == 'False'
    with (root/'strain_budget.csv').open(encoding='utf-8', newline='') as stream:
        budget = list(csv.DictReader(stream))
    assert len(budget) == 9
    assert all(float(r['required_overlap_parameter']) > 1 for r in budget)
    assert all(r['experimental_yield_MPa'] == '' and r['population_calibrated'] == 'False' for r in budget)


def test_executed_spatial_refinement_and_time_hold_are_not_yield():
    root = Path(__file__).resolve().parents[1]/'results/specimen_yield_bridge_v21'
    def read(name):
        with (root/(name+'.csv')).open(encoding='utf-8', newline='') as stream:
            return list(csv.DictReader(stream))
    rows = read('spatial_refinement')
    assert len(rows) == 36
    for span in (.2, 1., 5.):
        for angle in (.4, 1., 1.4):
            subset = [r for r in rows if float(r['span_um']) == span and float(r['endpoint_angle']) == angle]
            errors = [float(r['area_error_over_L_squared']) for r in subset]
            assert len(errors) == 4
            assert all(b < .35*a for a, b in zip(errors, errors[1:]))
    rows = read('unload_hold')
    assert len(rows) == 9
    assert all(float(r['final_to_peak']) < 1e-9 for r in rows)
    assert all(r['permanent_slip_generated'] == 'False' and r['experimental_yield_MPa'] == '' for r in rows)
    cycles = read('static_cycle_transport')
    assert len(cycles) == 297
    for row in cycles:
        assert abs(float(row['area_balance_residual_m2'])) < 1e-25
        if float(row['axial_stress_MPa']) == 0:
            assert float(row['axial_slip_strain']) == 0
    assert max(float(r['gross_area_m2']) for r in cycles) > 0
    # Completed run is bound to unchanged material/kinetic reference bytes.
    data = json.loads((root/'assessment.json').read_text(encoding='utf-8'))
    material = Path(__file__).resolve().parents[1]/data['material_path']
    assert hashlib.sha256(material.read_bytes()).hexdigest() == data['material_sha256']
    assert not data['material_accepted'] and not data['production_changed']
    assert data['actual_yield_prediction_MPa'] is None
